name: New Showcase entry
description: ONLY use this to submit information from the Showcase entry sheet. See the project handbook for details.
title: "[SHOWCASE]: "
labels: ["showcase"]
assignees:
  - eidolonnight
body:
  - type: markdown
    attributes:
      value:
        ONLY use this to submit information from the Showcase entry sheet. See the project handbook for details.
  - type: input
    id: site_url
    attributes:
      label: Site URL
      placeholder: ex. https://wordpress.org/news
    validations:
      required: true
  - type: input
    id: submission_date
    attributes:
      label: Submission date
      placeholder: ex. 24 May 2022
    validations:
      required: true
  - type: input
    id: submitter
    attributes:
      label: Submitter
      placeholder: ex. Wapuu
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      placeholder: ex. Wapuu
    validations:
      required: false
  - type: input
    id: theme
    attributes:
      label: Theme
      placeholder: ex. Twenty Twenty-four
    validations:
      required: false
  - type: input
    id: launch
    attributes:
      label: Launched On
      placeholder: ex. 24 May 2022
    validations:
      required: false
  - type: input
    id: country
    attributes:
      label: Country
      placeholder: ex. US
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason for Submission
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Any additional notes or details?
    validations:
      required: false